name: mdeal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+9

environment:
  sdk: ^3.10.0

msix_config:
  display_name: Monopoly Deal
  publisher_display_name: Levi Lesches
  identity_name: com.levi.monopoly-deal
  msix_version: 1.1.0.9
  logo_path: icon.jpg

resolution: workspace
dependencies:
  audioplayers: ^6.5.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  go_router: ^17.0.1
  shared: ^1.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  msix: ^3.16.12

flutter:
  uses-material-design: true

  assets:
    - images/
    - audio/

flutter_launcher_icons:
  image_path: icon.jpg
  android: true
  windows:
    generate: true
  web:
    generate: true
