name: mdeal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ^3.10.0

msix_config:
  display_name: Monopoly Deal
  publisher_display_name: Levi Lesches
  identity_name: com.levi.monopoly-deal
  msix_version: 1.0.0.7
  logo_path: icon.png

resolution: workspace
dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  shared: ^1.0.0

dev_dependencies:
  msix: ^3.16.12

flutter:
  uses-material-design: true
