name: mdeal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.10.0

resolution: workspace
dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  shared: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
