name: mdeal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  meta: ^1.17.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
