name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
resolution: workspace
dependencies:
  shared: ^1.0.0

dev_dependencies:
  test: ^1.25.6
