name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
resolution: workspace
dependencies:
  collection: ^1.19.1
  meta: ^1.17.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.25.6
