name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
resolution: workspace
dependencies:
  collection: ^1.19.1
  meta: ^1.17.0
  uuid: ^4.5.2

dev_dependencies:
  test: ^1.25.6
